it_job_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("people.urls", namespace="people")),
    path("", include("organization.urls", namespace="organization")),
    path("", include("operation.urls", namespace="operation")),
    path("accounts/", include("django.contrib.auth.urls")),
]

operation/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
)


app_name = "operation"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
]

organization/urls.py
from django.urls import path

from .views import (
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    TaskCreateProjectView,
    ProjectDeleteView,
    TeamAddProjectView,
)


app_name = "organization"

urlpatterns = [
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>/detail/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/add-task/", TaskCreateProjectView.as_view(), name="task-create-for-project"),
    path("projects/<int:pk>/add-team/", TeamAddProjectView.as_view(), name="project-add-team"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/detail/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
]

people/urls.py
from django.urls import path

from .views import (
    index,
    WorkerListView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerDeleteView,
)


app_name = "workspace"

urlpatterns = [
    path("", index, name="index"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
]

organization/models.py
from django.db import models
from people.models import Worker

from operation.models import Task


class Team(models.Model):
    name = models.CharField(max_length=255)
    workers = models.ManyToManyField(Worker)
    author = models.ForeignKey(Worker, on_delete=models.CASCADE, related_name="authored_team")

    class Meta:
        ordering = ["name",]
        indexes = [
            models.Index(fields=["name",])
        ]

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=500)
    teams = models.ManyToManyField(Team)
    author = models.ForeignKey(Worker, on_delete=models.CASCADE, related_name="authored_project")

    class Meta:
        ordering = ["name",]
        indexes = [
            models.Index(fields=["name",])
        ]

    def __str__(self):
        return f"Project {self.name}"

organization/forms.py
from django import forms

from .models import Project


class TeamSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-start",
                "placeholder": "Search by team name",
                "style": "height: 38px;"
            }
        )
    )


class ProjectSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-start",
                "placeholder": "Search by project name",
                "style": "height: 38px;",
            }
        )
    )


class ProjectTeamForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['teams']

organization/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

from operation.forms import TaskForm
from operation.models import Task

from .forms import ProjectSearchForm, TeamSearchForm, ProjectTeamForm
from .models import Project, Team


class TeamListView(LoginRequiredMixin, generic.ListView):
    model = Project
    template_name = "organization/team_list.html"
    context_object_name = "team_list"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TeamListView, self).get_context_data(**kwargs)
        context["search_form"] = TeamSearchForm()

        name = self.request.GET.get("name", "")

        context["search_form"] = TeamSearchForm(initial={"name": name})

        return context
    
    def get_queryset(self):
        queryset = Team.objects.all()
        form = TeamSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    model = Team
    template_name = "organization/team_detail.html"


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    fields = ("name", "workers",)
    template_name = "organization/team_form.html"
    success_url = reverse_lazy("organization:team-list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    

class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    fields = ("name", "workers",)
    template_name = "organization/team_update.html"
    success_url = reverse_lazy("organization:team-list")
    

class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Team
    success_url = reverse_lazy("organization:team-list")


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    template_name = "organization/project_list.html"
    context_object_name = "project_list"
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context["search_form"] = ProjectSearchForm()

        name = self.request.GET.get("name", "")

        context["search_form"] = ProjectSearchForm(initial={"name": name})

        return context
    
    def get_queryset(self):
        queryset = Project.objects.all()
        form = ProjectSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    template_name = "organization/project_detail.html"


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    fields = ("name", "description", "teams",)
    template_name = "organization/project_form.html"
    success_url = reverse_lazy("organization:project-list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskCreateProjectView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'operation/task_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.project = get_object_or_404(Project, pk=self.kwargs["pk"])
        return super().dispatch(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs
    
    def form_valid(self, form):
        form.instance.project = self.project
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("organization:project-detail", kwargs={"pk": self.project.pk})


class TeamAddProjectView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectTeamForm
    template_name = "organization/project_add_team.html"
    
    def get_success_url(self):
        return reverse("organization:project-detail", args=[self.object.pk])


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    fields = ("name", "description", "teams", "tasks",)
    template_name = "organization/project_update.html"
    success_url = reverse_lazy("organization:project-list")


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy("organization:project-list")

templates/organization/project_detail.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_tags %}

{% block title %} Team Create {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}


{% block content %}
  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5 text-white">
                {{ project.name }}
            </h1>
            {% if request.user == project.author or request.user.is_superuser %}
                <a class="btn btn-primary" href="{% url 'organization:task-create-for-project' pk=project.id %}">Add task</a>
                <a class="btn btn-primary" href="{% url 'organization:project-add-team' pk=project.id %}">Add team</a>
                <a class="btn btn-primary" href="{% url 'organization:project-delete' pk=project.id %}">Delete</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-5 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-4 px-4 blur shadow-blur bg-light">
          <p class="text-center mb-4">{{ project.description }}</p>
  
          <div class="row">
            <div class="col-md-6 border-end text-center">
              <h4 class="text-center mb-3 bg-white bg-opacity-10 d-inline-block text-gradient text-primary">
                Teams
              </h4>
              <div class="px-3">
                {% for team in project.teams.all %}
                  <h5 class="mb-2">
                    <a href="{% url 'organization:team-detail' pk=team.id %}" class="text-decoration-none text-dark">
                      {{ team.name }}
                    </a>
                  </h5>
                {% empty %}
                  <p class="text-muted">No teams available.</p>
                {% endfor %}
              </div>
            </div>
  
            <div class="col-md-6 text-center">
              <h4 class="text-center mb-3 bg-white bg-opacity-10 d-inline-block text-gradient text-primary">
                Tasks
              </h4>
              <div class="px-3">
                {% for task in project.tasks.all %}
                  <p class="mb-2">
                    <a href="{% url 'operation:task-detail' pk=task.id %}" class="text-decoration-none text-dark">
                      {{ task.name }}
                    </a>
                  </p>
                {% empty %}
                  <p class="text-muted">No tasks available.</p>
                {% endfor %}
              </div>
            </div>
          </div>
  
          <div class="text-center mt-4">
            <input type="button" value="Back" class="btn btn-secondary" onclick="history.back()">
          </div>
        </div>
      </div>
    </div>
  </section>
    
{% endblock %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/organization/project_list.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Project List {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5 text-white">
              Projects
            </h1>
            <a href="{% url 'organization:project-create' %}" class="btn btn-primary">Create</a>
            <form action="" method="get" class="form-inline">
                <div class="input-group">
                    {{ search_form.name }}
                    <div class="input-group-append">
                        <button class="btn btn-secondary rounded-end" type="submit" style="height: 38px;">🔍</button>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-5 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            {% for project in project_list %}
                <div class="col-md-4 position-relative">
                    <div class="p-3 text-center">
                        <h5 class="mt-3">
                            <a class="text-gradient text-primary font-weight-bolder" href="{% url 'organization:project-detail' pk=project.id %}">{{ project.name }}</a>
                        </h5>
                        <p class="text-sm">{{ project.description }}</p>
                    </div>
                    <hr class="vertical dark">
                </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/organization/team_detail.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_tags %}

{% block title %} Team Create {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}


{% block content %}
  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5 text-white">
              {{ team.name }}
            </h1>
            {% if request.user == team.author or request.user.is_superuser %}
                <a class="btn btn-primary" href="{% url 'organization:team-update' pk=team.id %}">Update</a>
                <a class="btn btn-primary" href="{% url 'organization:team-delete' pk=team.id %}">Delete</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-5 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur text-center">
            {% for worker in team.workers.all %}
                <h3><a href="{% url 'people:worker-detail' pk=worker.id %}">{{ worker.username }}</a></h3>
            {% endfor %}
            <input type="button" value="Back" class="btn btn-secondary" onclick="history.back()">
        </div>
      </div>
    </div>
  </section>
    
{% endblock %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/organization/team_list.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Team List {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5 text-white">
              Teams
            </h1>
            <a href="{% url 'organization:team-create' %}" class="btn btn-primary">Create</a>
            <form action="" method="get" class="form-inline">
                <div class="input-group">
                    {{ search_form.name }}
                    <div class="input-group-append">
                        <button class="btn btn-secondary rounded-end" type="submit" style="height: 38px;">🔍</button>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-5 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            {% for team in team_list %}
                <div class="col-md-4 position-relative">
                    <div class="p-3 text-center">
                        <h5 class="mt-3">
                            <a class="text-gradient text-primary font-weight-bolder" href="{% url 'organization:team-detail' pk=team.id %}">{{ team.name }}</a>
                        </h5>
                        {% for worker in team.workers.all %}
                            <p class="text-sm"><a href="{% url 'people:worker-detail' pk=worker.id %}">{{ worker.username }}</a></p>
                        {% endfor %}
                    </div>
                    <hr class="vertical dark">
                </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}