it_job_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("people.urls", namespace="people")),
    path("", include("organization.urls", namespace="organization")),
    path("", include("operation.urls", namespace="operation")),
    path("accounts/", include("django.contrib.auth.urls")),
]

operation/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
)


app_name = "operation"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
]

organization/urls.py
from django.urls import path

from .views import (
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    TaskCreateProjectView,
    ProjectDeleteView,
    TeamAddProjectView,
)


app_name = "organization"

urlpatterns = [
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>/detail/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/add-task/", TaskCreateProjectView.as_view(), name="task-create-for-project"),
    path("projects/<int:pk>/add-team/", TeamAddProjectView.as_view(), name="project-add-team"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/detail/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
]

people/urls.py
from django.urls import path

from .views import (
    index,
    WorkerListView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerDeleteView,
)


app_name = "workspace"

urlpatterns = [
    path("", index, name="index"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
]

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="text-center">
          <p class="my-4 text-sm">
            <a href="https://github.com/Fantom245/IT_job_manager" target="_blank" class="text-gradient text-primary font-weight-bolder">Django Project For Portfolio</a> 
            - Coded by <a target="_blank" href="https://github.com/Fantom245" target="_blank">Fantom245</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Soft UI Design System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" 
                     href="https://appseed.us/support/" target="_blank">
                    <i class="fa fa-rocket me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Get Free Support">Support</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="https://appseed.us/product/soft-ui-design-pro/django/" 
                     target="_blank" 
                     class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">PRO Version</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <nav class="top-0 z-index-fixed position-absolute my-3 py-2 start-0 end-0">
        <div class="d-flex justify-content-between align-items-center">
          <a class="btn btn-link nav-btn d-flex align-items-center text-decoration-none p-1" style="font-size: 0.9rem; color: white;" href="/">
            <i class="fa fa-home me-1" style="font-size: 1rem;"></i>
            <span>Home</span>
          </a>
          <div class="d-flex">
            {% if user.is_authenticated %}
              <form method="post" action="{% url 'logout' %}" class="d-flex align-items-center">
                {% csrf_token %}
                <button type="submit" class="btn btn-link d-flex align-items-center text-decoration-none p-1" style="font-size: 0.9rem;">
                  <i class="fa fa-sign-out me-1" style="font-size: 1rem;"></i>
                  <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</span>
                </button>
              </form>
            {% else %}
              <a class="btn btn-link nav-btn d-flex align-items-center text-decoration-none p-1" style="font-size: 0.9rem;" href="{% url 'login' %}">
                <i class="fa fa-sign-in me-1" style="font-size: 1rem;"></i>
                <span>Login</span>
              </a>
              <a class="btn btn-link nav-btn d-flex align-items-center text-decoration-none p-1" style="font-size: 0.9rem;" href="{% url 'people:worker-create' %}">
                <i class="fa fa-user-plus me-1" style="font-size: 1rem;"></i>
                <span>Registration</span>
              </a>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %} " class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
    {% if user.is_authenticated %}
        {{ user.username }}
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn-primary"></input>
        </form>
    {% else %}
        <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
        <li class="list-group-item"><a href="{% url 'people:worker-create' %}">Registration</a></li>
    {% endif %}
    <br>
    <li class="list-group-item"><a href="{% url 'workspace:index' %}">Home</a></li>
    <li class="list-group-item"><a href="{% url 'operation:task-list' %}">Task List</a></li>
    <li class="list-group-item"><a href="{% url 'workspace:worker-list' %}">Worker List</a></li>
    <li class="list-group-item"><a href="{% url 'organization:team-list' %}">Team List</a></li>
    <li class="list-group-item"><a href="{% url 'organization:project-list' %}">Project List</a></li>
</ul>